<<<<<<< HEAD
# BUILDING AND RUNNING: docker compose up -d --build
# LOGGING: docker logs booking-system-phase3-web-1 -f
# CONNECTING TO CONTAINER: docker exec -it booking-system-phase3-web-1 /bin/sh
# REMOVING: docker compose down --volumes
# REMOVING IMAGE (IF NEEDED): docker rmi bs-phase3
name: booking-system-phase3
services:
  web:
    build: .
    image: bs-phase3
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

=======
# BUILDING AND RUNNING: docker compose up -d --build
# LOGGING: docker logs booking-system-phase2 -f
# CONNECTING TO CONTAINER: docker exec -it booking-system-phase2 /bin/sh
# REMOVING: docker compose down --volumes
# REMOVING IMAGE (IF NEEDED): docker rmi bs-phase2
name: booking-system-phase2
services:
  web:
    build: .
    image: bs-phase2
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/share/nginx/html
>>>>>>> ba7a9eb6fe8d04382e907cb27fa58af5a1f0588b
